# Generated by Django 4.1.4 on 2022-12-26 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_notification_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(choices=[("match", "match")], max_length=15),
        ),
    ]
