# Generated by Django 4.1.4 on 2022-12-30 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_alter_match_time_alter_notification_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sex_identity",
            field=models.TextField(
                choices=[("m", "MALE"), ("f", "FEMALE"), ("b", "BOTH"), ("o", "OTHER")]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex_preference",
            field=models.TextField(
                choices=[("m", "MALE"), ("f", "FEMALE"), ("b", "BOTH"), ("o", "OTHER")]
            ),
        ),
    ]
