# Generated by Django 4.1.4 on 2022-12-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_sex_identity_alter_user_sex_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
