# Generated by Django 4.1.4 on 2023-01-01 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_latitude_alter_user_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="loc_update_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
