# Generated by Django 4.1.4 on 2023-01-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_loc_update_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sex_identity",
            field=models.TextField(
                choices=[("m", "MALE"), ("f", "FEMALE"), ("b", "BOTH")]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex_preference",
            field=models.TextField(
                choices=[("m", "MALE"), ("f", "FEMALE"), ("b", "BOTH")]
            ),
        ),
    ]
