# Generated by Django 4.1.4 on 2023-01-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_user_sex_identity_alter_user_sex_preference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="type", new_name="category",
        ),
    ]
