# Generated by Django 4.1.4 on 2023-01-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_rename_type_question_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification", name="sound", field=models.TextField(null=True),
        ),
    ]
