# Generated by Django 4.1.4 on 2023-01-09 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_notification_sound"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_matchable",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
