# Generated by Django 4.1.4 on 2023-01-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_is_matchable_alter_question_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="accept_notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="initial_notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="user1_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="user2_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("match", "match"), ("accept", "accept")], max_length=15
            ),
        ),
    ]
