# Generated by Django 4.1.4 on 2023-01-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_remove_question_answer_remove_question_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_numerical",
            field=models.BooleanField(default=False),
        ),
    ]
