# Generated by Django 4.1.4 on 2023-01-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_question_is_numerical"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_multiple_answer",
            field=models.BooleanField(default=False),
        ),
    ]
