# Generated by Django 4.1.4 on 2023-01-14 02:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_question_is_multiple_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="text_answer_choices",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), default=[], size=None
            ),
        ),
    ]
