# Generated by Django 4.1.4 on 2023-01-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial_squashed_0023_question_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="header",
            field=models.TextField(
                choices=[
                    (0, "personality"),
                    (1, "preferences"),
                    (2, "values"),
                    (3, "lifestyle"),
                ],
                default="personality",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.TextField(
                choices=[
                    (0, "organized/chaotic"),
                    (1, "extraverted/introverted"),
                    (2, "sentimental/stoic"),
                    (3, "empathetic/intellectual"),
                    (4, "bold/patient"),
                    (5, "spontaneous/intentional"),
                    (6, "timely/flexible"),
                    (7, "agreeable/strong-willed"),
                    (8, "family-oriented/career-oriented"),
                    (9, "frugal/bougie"),
                    (10, "dog-lover/cat-lover"),
                    (11, "academic/artistic"),
                    (12, "minimalistic/materialistic"),
                    (13, "self-aware/blissfully-unaware"),
                    (14, "prudent/yolo"),
                    (15, "laid-back/straightedge"),
                    (16, "attentive/idgaf"),
                    (17, "early-bird/night-owl"),
                    (18, "open-minded/disciplined"),
                    (19, "languages"),
                    (20, "love-languages"),
                    (21, "politics"),
                    (22, "religion"),
                    (23, "diet"),
                    (24, "drugs"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="question", name="prompt", field=models.TextField(),
        ),
    ]
