# Generated by Django 4.1.4 on 2023-01-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_alter_question_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="avg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="std_dev",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
