# Generated by Django 4.1.4 on 2023-01-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_question_avg_question_std_dev"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="avg",),
        migrations.RemoveField(model_name="question", name="std_dev",),
        migrations.AddField(
            model_name="question", name="average", field=models.FloatField(default=0),
        ),
    ]
