# Generated by Django 4.1.4 on 2023-01-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_question_maximum_question_minimum_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trait1", models.TextField()),
                ("trait2", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TextQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.TextField()),
                ("prompt", models.TextField()),
                ("is_multiple_answer", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="text_questions",
                        to="users.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TextAnswerChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emoji", models.TextField()),
                ("answer", models.TextField()),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="text_answer_choices",
                        to="users.textquestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NumericalQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.TextField()),
                ("prompt", models.TextField()),
                ("average", models.FloatField(default=3)),
                ("variance", models.FloatField(default=1)),
                ("minimum", models.FloatField(default=0)),
                ("maximum", models.FloatField(default=6)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="numerical_questions",
                        to="users.category",
                    ),
                ),
            ],
        ),
    ]
