# Generated by Django 4.1.4 on 2023-01-21 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_category_textquestion_textanswerchoice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("header", models.TextField()),
                ("prompt", models.TextField()),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="text_questions",
                        to="users.category",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="numericalquestion", name="category",),
        migrations.RemoveField(model_name="numericalquestion", name="header",),
        migrations.RemoveField(model_name="numericalquestion", name="prompt",),
        migrations.RemoveField(model_name="textquestion", name="category",),
        migrations.RemoveField(model_name="textquestion", name="header",),
        migrations.RemoveField(model_name="textquestion", name="prompt",),
        migrations.AlterField(
            model_name="numericalresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="numerical_responses",
                to="users.numericalquestion",
            ),
        ),
        migrations.AlterField(
            model_name="textresponse",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_responses",
                to="users.textquestion",
            ),
        ),
        migrations.DeleteModel(name="Question",),
        migrations.AddField(
            model_name="numericalquestion",
            name="base_question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="numerical_question",
                to="users.basequestion",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="textquestion",
            name="base_question",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="text_question",
                to="users.basequestion",
            ),
            preserve_default=False,
        ),
    ]
