# Generated by Django 4.1.4 on 2023-01-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_basequestion_remove_numericalquestion_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="numericalquestion",
            old_name="base_question",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="textquestion", old_name="base_question", new_name="question",
        ),
    ]
