# Generated by Django 4.1.4 on 2023-01-21 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_rename_base_question_numericalquestion_question_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="numericalquestion",
            old_name="question",
            new_name="base_question",
        ),
        migrations.RenameField(
            model_name="textquestion", old_name="question", new_name="base_question",
        ),
        migrations.AlterField(
            model_name="basequestion",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="users.category",
            ),
        ),
    ]
