# Generated by Django 4.1.6 on 2023-02-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_alter_notification_message_alter_notification_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message", old_name="timestamp", new_name="datetime",
        ),
    ]
