# Generated by Django 4.1.6 on 2023-02-12 22:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_rename_timestamp_message_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="timestamp",
            field=models.FloatField(default=users.models.current_timestamp),
        ),
    ]
