# Generated by Django 4.1.7 on 2023-02-16 00:17

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_remove_message_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.User.picture_filepath
            ),
        ),
    ]
